package com.lianpay.globalpay.enums;


import java.util.HashMap;
import java.util.Map;


public enum CourierEnum {
    fedex("fedex", "Fedex", "Fedex-联邦快递"),
    dhl("dhl", "DHL", "DHL"),
    ups("ups", "UPS", "UPS"),
    tnt("tnt", "TNT", "TNT"),
    china_post("china-post", "China Post", "中国邮政"),
    china_ems("china-ems", "China EMS", "中国 EMS"),
    hong_kong_post("hong-kong-post", "Hong Kong Post", "香港邮政"),
    singapore_post("singapore-post", "Singapore Post", "新加坡邮政(小包)"),
    swiss_post("swiss-post", "Swiss Post", "瑞士邮政"),
    usps("usps", "USPS", "美国邮政"),
    royal_mail("royal-mail", "United Kingdom Royal Mail", "英国皇家邮政"),
    postnl_parcels("postnl-parcels", "Netherlands Post - PostNL", "荷兰邮政-PostNL"),
    canada_post("canada-post", "Canada Post", "加拿大邮政"),
    australia_post("australia-post", "Australia Post", "澳大利亚邮政"),
    new_zealand_post("new-zealand-post", "New Zealand Post", "新西兰邮政"),
    parcel_force("parcel-force", "Parcel Force", "英国邮政parcelforce"),
    belgium_post("belgium-post", "Bpost", "比利时邮政"),
    brazil_correios("brazil-correios", "Brazil Correios", "巴西邮政"),
    russian_post("russian-post", "Russian Post", "俄罗斯邮政"),
    sweden_posten("sweden-posten", "Sweden Posten", "瑞典邮政"),
    laposte("laposte", "La Poste", "法国邮政-La Poste"),
    poste_italiane("poste-italiane", "Poste Italiane", "意大利邮政"),
    aland_post("aland-post", "Åland Post", "奥兰群岛芬兰邮政"),
    afghan_post("afghan-post", "Afghan Post", "阿富汗邮政"),
    posta_shqiptare("posta-shqiptare", "Albania Post", "阿尔巴尼亚邮政"),
    andorra_post("andorra-post", "Andorra Post", "安道尔邮政"),
    antilles_post("antilles-post", "Antilles Post", "荷属安的列斯荷兰邮政"),
    correo_argentino("correo-argentino", "Argentina Post", "阿根廷邮政"),
    armenia_post("armenia-post", "Armenia Post", "亚美尼亚邮政"),
    aruba_post("aruba-post", "Aruba Post", "阿鲁巴邮政"),
    australia_ems("australia-ems", "Australia EMS", "澳大利亚 EMS"),
    austria_post("austria-post", "Austrian Post", "奥地利邮政"),
    azerbaijan_post("azerbaijan-post", "Azerbaijan Post", "阿塞拜疆邮政"),
    bahrain_post("bahrain-post", "Bahrain Post", "巴林邮政"),
    bangladesh_ems("bangladesh-ems", "Bangladesh EMS", "孟加拉国 EMS"),
    barbados_post("barbados-post", "Barbados Post", "巴巴多斯邮政"),
    belpochta("belpochta", "Belarus Post", "白俄罗斯邮政"),
    belize_post("belize-post", "Belize Post", "伯利兹邮政"),
    benin_post("benin-post", "Benin Post", "贝宁邮政"),
    bermuda_post("bermuda-post", "Bermuda Post", "百慕大邮政"),
    bhutan_post("bhutan-post", "Bhutan Post", "不丹邮政"),
    correos_bolivia("correos-bolivia", "Bolivia Post", "玻利维亚邮政"),
    bosnia_and_herzegovina_post("bosnia-and-herzegovina-post", "Bosnia And Herzegovina Post", "波黑邮政"),
    botswana_post("botswana-post", "Botswana Post", "博茨瓦纳邮政"),
    brunei_post("brunei-post", "Brunei Post", "文莱邮政"),
    bulgaria_post("bulgaria-post", "Bulgaria Post", "保加利亚邮政"),
    sonapost("sonapost", "Burkina Faso Post", "布基纳法索邮政"),
    burundi_post("burundi-post", "Burundi Post", "布隆迪邮政"),
    cambodia_post("cambodia-post", "Cambodia Post", "柬埔寨邮政"),
    campost("campost", "Cameroon Post", "喀麦隆邮政"),
    correos_chile("correos-chile", "Correos Chile", "智利邮政"),
    colombia_post("colombia-post", "Colombia Post", "哥伦比亚邮政"),
    correos_de_costa_rica("correos-de-costa-rica", "Costa Rica Post", "哥斯达黎加邮政"),
    hrvatska_posta("hrvatska-posta", "Croatia Post", "克罗地亚邮政"),
    cuba_post("cuba-post", "Cuba Post", "古巴邮政"),
    cyprus_post("cyprus-post", "Cyprus Post", "塞浦路斯邮政"),
    czech_post("czech-post", "Česká Pošta", "捷克邮政"),
    denmark_post("denmark-post", "Denmark post", "丹麦邮政"),
    correos_del_ecuador("correos-del-ecuador", "Ecuador Post", "厄瓜多尔邮政"),
    egypt_post("egypt-post", "Egypt Post", "埃及邮政"),
    el_salvador_post("el-salvador-post", "El Salvador Post", "萨尔瓦多邮政"),
    eritrea_post("eritrea-post", "Eritrea Post", "厄立特里亚邮政"),
    omniva("omniva", "Estonia Post", "爱沙尼亚邮政"),
    ethiopia_post("ethiopia-post", "Ethiopia Post", "埃塞俄比亚邮政"),
    faroe_islands_post("faroe-islands-post", "Faroe Islands Post", "法罗群岛邮政"),
    fiji_post("fiji-post", "Fiji Post", "斐济邮政"),
    finland_posti("finland-posti", "Finland Post - Posti", "芬兰邮政-Posti"),
    colissimo("colissimo", "Colissimo", "法国邮政-Colissimo"),
    chronopost("chronopost", "France EMS - Chronopost", "法国 EMS-Chronopost"),
    georgian_post("georgian-post", "Georgia Post", "格鲁吉亚邮政"),
    deutsche_post("deutsche-post", "Deutsche Post", "德国邮政"),
    ghana_post("ghana-post", "Ghana Post", "加纳邮政"),
    gibraltar_post("gibraltar-post", "Gibraltar  Post", "直布罗陀邮政"),
    greece_post("greece-post", "ELTA Hellenic Post", "希腊邮政"),
    tele_post("tele-post", "Greenland Post", "格陵兰岛邮政"),
    elcorreo("elcorreo", "Guatemala Post", "危地马拉邮政"),
    guernsey_post("guernsey-post", "Guernsey Post", "根西岛邮政"),
    magyar_posta("magyar-posta", "Magyar Posta", "匈牙利邮政"),
    iceland_post("iceland-post", "Iceland Post", "冰岛邮政"),
    india_post("india-post", "India Post", "印度邮政"),
    indonesia_post("indonesia-post", "Indonesia Post", "印度尼西亚邮政"),
    iran_post("iran-post", "Iran Post", "伊朗邮政"),
    an_post("an-post", "An Post", "爱尔兰邮政"),
    israel_post("israel-post", "Israel Post", "以色列邮政"),
    ivory_coast_ems("ivory-coast-ems", "Ivory Coast EMS", "科特迪瓦 EMS"),
    jamaica_post("jamaica-post", "Jamaica Post", "牙买加邮政"),
    japan_post("japan-post", "Japan Post", "日本邮政"),
    jordan_post("jordan-post", "Jordan Post", "约旦邮政"),
    kazpost("kazpost", "Kazakhstan Post", "哈萨克斯坦邮政"),
    kenya_post("kenya-post", "Kenya Post", "肯尼亚邮政"),
    korea_post("korea-post", "Korea Post", "韩国邮政"),
    kyrgyzpost("kyrgyzpost", "Kyrgyzstan Post", "吉尔吉斯斯坦邮政"),
    laos_post("laos-post", "Laos Post", "老挝邮政"),
    latvijas_pasts("latvijas-pasts", "Latvia Post", "拉脱维亚邮政"),
    liban_post("liban-post", "Lebanon Post", "黎巴嫩邮政"),
    lesotho_post("lesotho-post", "Lesotho Post", "莱索托邮政"),
    liechtenstein_post("liechtenstein-post", "Liechtenstein Post", "列支敦士登邮政"),
    lietuvos_pastas("lietuvos-pastas", "Lithuania Post", "立陶宛邮政"),
    luxembourg_post("luxembourg-post", "Luxembourg Post", "卢森堡邮政"),
    macao_post("macao-post", "Macao Post", "澳门邮政"),
    macedonia_post("macedonia-post", "Macedonia Post", "马其顿邮政"),
    malaysia_post("malaysia-post", "Malaysia Post", "马来西亚邮政"),
    maldives_post("maldives-post", "Maldives Post", "马尔代夫邮政"),
    malta_post("malta-post", "Malta Post", "马耳他邮政"),
    mauritius_post("mauritius-post", "Mauritius Post", "毛里求斯邮政"),
    correos_mexico("correos-mexico", "Mexico Post", "墨西哥邮政"),
    moldova_post("moldova-post", "Moldova Post", "摩尔多瓦邮政"),
    la_poste_monaco("la-poste-monaco", "Monaco Post", "摩纳哥邮政"),
    monaco_ems("monaco-ems", "Monaco EMS", "摩纳哥 EMS"),
    mongol_post("mongol-post", "Mongol Post", "蒙古邮政"),
    posta_crne_gore("posta-crne-gore", "Montenegro Post", "黑山邮政"),
    poste_maroc("poste-maroc", "Maroc Poste", "摩洛哥邮政"),
    namibia_post("namibia-post", "Namibia Post", "纳米比亚邮政"),
    netherlands_post("netherlands-post", "Netherlands Post", "荷兰邮政(大包)"),
    new_caledonia_post("new-caledonia-post", "New Caledonia Post", "新喀里多尼亚邮政"),
    nicaragua_post("nicaragua-post", "Nicaragua Post", "尼加拉瓜邮政"),
    nigeria_post("nigeria-post", "Nigeria Post", "尼日利亚邮政"),
    posten_norge("posten-norge", "Posten Norge", "挪威邮政"),
    oman_post("oman-post", "Oman Post", "阿曼邮政"),
    overseas_territory_fr_ems("overseas-territory-fr-ems", "Overseas Territory FR EMS", "海外领地法国 EMS"),
    overseas_territory_us_post("overseas-territory-us-post", "Overseas Territory US Post", "海外领地美国邮政"),
    pakistan_post("pakistan-post", "Pakistan Post", "巴基斯坦邮政"),
    correos_panama("correos-panama", "Panama Post", "巴拿马邮政"),
    postpng("postpng", "Papua New Guinea Post", "巴布亚新几内亚邮政"),
    correo_paraguayo("correo-paraguayo", "Paraguay Post", "巴拉圭邮政"),
    serpost("serpost", "Serpost", "秘鲁邮政"),
    phlpost("phlpost", "Philippines Post", "菲律宾邮政"),
    poczta_polska("poczta-polska", "Poland Post", "波兰邮政"),
    ctt("ctt", "Portugal Post - CTT", "葡萄牙邮政-CTT"),
    posta_romana("posta-romana", "Poșta Română", "罗马尼亚邮政"),
    iposita_rwanda("iposita-rwanda", "Rwanda Post", "卢旺达邮政"),
    saint_lucia_post("saint-lucia-post", "Saint Lucia Post", "圣卢西亚邮政"),
    svgpost("svgpost", "Saint Vincent And The Grenadines", "圣文森特和格林纳丁斯"),
    samoa_post("samoa-post", "Samoa Post", "西萨摩亚邮政"),
    san_marino_post("san-marino-post", "San Marino Post", "圣马力诺邮政"),
    saudi_post("saudi-post", "Saudi Post", "沙特阿拉伯邮政"),
    senegal_post("senegal-post", "Senegal Post", "塞内加尔邮政"),
    serbia_post("serbia-post", "Serbia Post", "塞尔维亚邮政"),
    seychelles_post("seychelles-post", "Seychelles Post", "塞舌尔邮政"),
    slovakia_post("slovakia-post", "Slovakia Post", "斯洛伐克邮政"),
    slovenia_post("slovenia-post", "Slovenia Post", "斯洛文尼亚邮政"),
    solomon_post("solomon-post", "Solomon Post", "所罗门群岛邮政"),
    south_africa_post("south-africa-post", "South African Post Office", "南非邮政"),
    correos_spain("correos-spain", "Correos", "西班牙邮政"),
    sri_lanka_post("sri-lanka-post", "Sri Lanka Post", "斯里兰卡邮政"),
    sudan_post("sudan-post", "Sudan Post", "苏丹邮政"),
    syrian_post("syrian-post", "Syrian Post", "叙利亚邮政"),
    taiwan_post("taiwan-post", "Taiwan Post", "台湾邮政"),
    tanzania_post("tanzania-post", "Tanzania Post", "坦桑尼亚邮政"),
    thailand_post("thailand-post", "Thailand Post", "泰国邮政"),
    togo_post("togo-post", "Togo Post", "多哥邮政"),
    tonga_post("tonga-post", "Tonga Post", "汤加邮政"),
    tunisia_post("tunisia-post", "Tunisia Post", "突尼斯邮政"),
    turkey_post("turkey-post", "Turkey Post", "土耳其邮政"),
    uganda_post("uganda-post", "Uganda Post", "乌干达邮政"),
    ukraine_post("ukraine-post", "Ukraine Post", "乌克兰邮政"),
    ukraine_ems("ukraine-ems", "Ukraine EMS", "乌克兰 EMS"),
    emirates_post("emirates-post", "Emirates Post", "阿联酋邮政"),
    uruguay_post("uruguay-post", "Uruguay Post", "乌拉圭邮政"),
    uzbekistan_post("uzbekistan-post", "Uzbekistan Post", "乌兹别克斯坦邮政"),
    vanuatu_post("vanuatu-post", "Vanuatu Post", "瓦努阿图邮政"),
    vietnam_post("vietnam-post", "Vietnam Post", "越南邮政"),
    yemen_post("yemen-post", "Yemen Post", "也门邮政"),
    zambia_post("zambia-post", "Zambia Post", "赞比亚邮政"),
    zimbabwe_post("zimbabwe-post", "Zimbabwe Post", "津巴布韦邮政"),
    singapore_speedpost("singapore-speedpost", "Singapore Speedpost", "新加坡特快专递"),
    yanwen("yanwen", "YANWEN", "燕文"),
    gls("gls", "GLS", "GLS"),
    bartolini("bartolini", "BRT Bartolini", "BRT Bartolini"),
    dpd("dpd", "DPD", "DPD"),
    sfb2c("sfb2c", "SF International", "顺丰国际"),
    aramex("aramex", "Aramex", "Aramex"),
    toll("toll", "TOLL", "TOLL"),
    dhl_germany("dhl-germany", "Deutsche Post DHL", "德国DHL"),
    _4px("4px", "4PX", "递四方"),
    flytexpress("flytexpress", "Flyt Express", "飞特物流"),
    yunexpress("yunexpress", "Yun Express", "云途物流"),
    oneworldexpress("oneworldexpress", "One World Express", "万欧国际"),
    dhlparcel_nl("dhlparcel-nl", "DHL Parcel Netherlands", "荷兰DHL"),
    dhl_poland("dhl-poland", "DHL Poland Domestic", "波兰DHL"),
    dhl_es("dhl-es", "DHL Spain Domestic", "西班牙DHL"),
    tnt_it("tnt-it", "TNT Italy", "意大利TNT"),
    tnt_fr("tnt-fr", "TNT France", "法国TNT"),
    dpd_uk("dpd-uk", "DPD UK", "DPD UK"),
    tnt_uk("tnt-uk", "TNT UK", "TNT UK"),
    gls_italy("gls-italy", "GLS Italy", "意大利GLS"),
    toll_ipec("toll-ipec", "Toll IPEC", "Toll IPEC"),
    asendia_usa("asendia-usa", "Asendia USA", "Asendia USA"),
    asendia_uk("asendia-uk", "Asendia UK", "Asendia UK"),
    yodel("yodel", "Yodel", "Yodel"),
    asendia_de("asendia-de", "Asendia Germany", "Asendia Germany"),
    kerry_logistics("kerry-logistics", "Kerry Express", "嘉里大通物流"),
    xru("xru", "XRU", "XRU-俄速递"),
    dpex("dpex", "DPEX", "DPEX"),
    ruston("ruston", "Ruston", "Ruston俄速通"),
    upu("upu", "UPU", "UPU"),
    bluedart("bluedart", "Bluedart", "Bluedart"),
    dtdc("dtdc", "DTDC", "DTDC"),
    gojavas("gojavas", "GoJavas", "GoJavas"),
    first_flight("first-flight", "First Flight", "First Flight"),
    gati_kwe("gati-kwe", "Gati-KWE", "Gati-KWE"),
    rosan("rosan", "ROSAN EXPRESS", "中乌融盛速递"),
    wsgd_logistics("wsgd-logistics", "WSGD Logistics", "WSGD物流"),
    wishpost("wishpost", "WishPost", "Wish邮"),
    sto("sto", "STO Express", "申通快递"),
    yto("yto", "YTO Express", "圆通快递"),
    zto("zto", "ZTO Express", "中通快递"),
    dhlglobalmail("dhlglobalmail", "DHL ECommerce", "DHL电子商务"),
    dsv("dsv", "DSV", "DSV"),
    echo("echo", "Echo", "Echo"),
    dpd_ireland("dpd-ireland", "DPD Ireland", "爱尔兰DPD"),
    ontrac("ontrac", "OnTrac", "OnTrac"),
    purolator("purolator", "Purolator", "Purolator"),
    fastway_nz("fastway-nz", "Fastway New Zealand", "新西兰Fastway"),
    fastway_au("fastway-au", "Fastway Australia", "澳大利亚Fastway"),
    fastway_ie("fastway-ie", "Fastway Ireland", "爱尔兰Fastway"),
    i_parcel("i-parcel", "I-parcel", "I-parcel"),
    lasership("lasership", "Lasership", "Lasership"),
    skynetworldwide("skynetworldwide", "SkyNet Worldwide Express", "SkyNet国际快递"),
    pfcexpress("pfcexpress", "PFC Express", "PFC皇家物流"),
    nexive("nexive", "Nexive", "Nexive"),
    overnitenet("overnitenet", "Overnite Express", "Overnite印度快递"),
    rl_carriers("rl-carriers", "RL Carriers", "RL Carriers"),
    nanjingwoyuan("nanjingwoyuan", "Nanjing Woyuan", "南京沃源"),
    lwehk("lwehk", "LWE", "LWE"),
    hhexp("hhexp", "Hua Han Logistics", "华翰物流"),
    envialia("envialia", "Envialia", "Envialia"),
    canpar("canpar", "Canpar Courier", "Canpar Courier"),
    _17postservice("17postservice", "17 Post Service", "17 Post Service"),
    delcart_in("delcart-in", "Delcart", "Delcart"),
    citylinkexpress("citylinkexpress", "City-Link Express", "City-Link(信递联）"),
    _2go("2go", "2GO", "2GO"),
    xend("xend", "Xend Express", "Xend"),
    air21("air21", "AIR21", "AIR21"),
    airspeed("airspeed", "Airspeed International Corporation", "Airspeed International Corporation"),
    raf("raf", "RAF Philippines", "RAF Philippines"),
    tiki("tiki", "Tiki", "Tiki"),
    wahana("wahana", "Wahana", "Wahana"),
    ghn("ghn", "Giao Hàng Nhanh", "Giao Hàng Nhanh"),
    viettelpost("viettelpost", "Viettel Post", "Viettel Post"),
    dotzot("dotzot", "Dotzot", "Dotzot"),
    kangaroo_my("kangaroo-my", "Kangaroo Worldwide Express", "Kangaroo Worldwide Express"),
    cuckooexpress("cuckooexpress", "Cuckoo Express", "布谷鸟速递"),
    maxcellents("maxcellents", "Maxcellents Pte Ltd", "Maxcellents Pte Ltd"),
    nationwide_my("nationwide-my", "Nationwide Express", "Nationwide Express"),
    rpxonline("rpxonline", "RPX Online", "RPX保时达国际快递"),
    nhans_solutions("nhans-solutions", "Nhans Solutions", "Nhans Solutions"),
    jet_ship("jet-ship", "Jet-Ship Worldwide", "Jet-Ship Worldwide"),
    ecargo_asia("ecargo-asia", "Ecargo", "Ecargo"),
    delhivery("delhivery", "Delhivery", "Delhivery"),
    nuvoex("nuvoex", "NuvoEx", "NuvoEx"),
    parcelled_in("parcelled-in", "Parcelled.in", "Parcelled.in"),
    ecom_express("ecom-express", "Ecom Express", "Ecom Express"),
    gdex("gdex", "GDEX", "GDEX"),
    skynet("skynet", "SkyNet Malaysia", "SkyNet"),
    sfcservice("sfcservice", "SFC Service", "三态速递"),
    ec_firstclass("ec-firstclass", "EC-Firstclass", "EC-Firstclass"),
    wedo("wedo", "WeDo Logistics", "WeDo Logistics"),
    jcex("jcex", "JCEX", "JCEX佳成"),
    cnexps("cnexps", "CNE Express", "CNE国际快递"),
    equick_cn("equick-cn", "Equick China", "EQUICK国际快递"),
    empsexpress("empsexpress", "EMPS Express", "EMPS Express"),
    cpacket("cpacket", "CPacket", "CPacket"),
    dpe_express("dpe-express", "DPE Express", "递必易"),
    bondscouriers("bondscouriers", "Bonds Couriers", "Bonds Couriers"),
    courierpost("courierpost", "CourierPost", "CourierPost"),
    acommerce("acommerce", "ACOMMERCE", "ACommerce"),
    _139express("139express", "139 ECONOMIC Package", "139快递"),
    ubi_logistics("ubi-logistics", "UBI Logistics", "UBI Logistics"),
    directfreight_au("directfreight-au", "Direct Freight", "Direct Freight快递"),
    mrw_spain("mrw-spain", "MRW", "MRW"),
    packlink("packlink", "Packlink", "Packlink"),
    colis_prive("colis-prive", "Colis Privé", "Colis Privé"),
    dmm_network("dmm-network", "DMM Network", "DMM Network"),
    opek("opek", "FedEx Poland Domestic", "波兰FedEx"),
    sgt_it("sgt-it", "SGT Corriere Espresso", "SGT Corriere Espresso"),
    kgmhub("kgmhub", "KGM Hub", "KGM Hub"),
    qxpress("qxpress", "Qxpress", "Qxpress"),
    parcel_express("parcel-express", "Parcel Express", "Parcel Express"),
    srekorea("srekorea", "SRE Korea", "SRE Korea"),
    taqbin_jp("taqbin-jp", "Yamato Japan", "Yamato宅急便"),
    sagawa("sagawa", "Sagawa", "佐川急便Sagawa"),
    abxexpress_my("abxexpress-my", "ABX Express", "ABX Express"),
    mypostonline("mypostonline", "Mypostonline", "Mypostonline"),
    jam_express("jam-express", "Jam Express", "Jam Express"),
    jayonexpress("jayonexpress", "Jayon Express (JEX)", "Jayon Express (JEX)"),
    rpx("rpx", "RPX Indonesia", "RPX Indonesia"),
    raiderex("raiderex", "RaidereX", "RaidereX"),
    rzyexpress("rzyexpress", "RZY Express", "RZY Express"),
    airpak_express("airpak-express", "Airpak Express", "Airpak Express"),
    lbcexpress("lbcexpress", "LBC Express", "LBC Express"),
    pandulogistics("pandulogistics", "Pandu Logistics", "Pandu Logistics"),
    fedex_uk("fedex-uk", "FedEx UK", "英国FedEx"),
    collectplus("collectplus", "Collect+", "Collect+"),
    skynetworldwide_uk("skynetworldwide-uk", "Skynet Worldwide Express UK", "Skynet Worldwide Express UK"),
    hermes("hermes", "Hermesworld", "Hermesworld"),
    nightline("nightline", "Nightline", "Nightline"),
    apc("apc", "APC Postal Logistics", "APC Postal Logistics"),
    newgistics("newgistics", "Newgistics", "Newgistics"),
    old_dominion("old-dominion", "Old Dominion Freight Line", "Old Dominion Freight Line"),
    estes("estes", "Estes", "Estes"),
    greyhound("greyhound", "Greyhound", "Greyhound"),
    globegistics("globegistics", "Globegistics Inc", "Globegistics Inc"),
    tgx("tgx", "TGX", "TGX精英速运"),
    zjs_express("zjs-express", "ZJS International", "宅急送快递"),
    hermes_de("hermes-de", "Hermes Germany", "德国Hermes"),
    international_seur("international-seur", "International Seur", "International Seur"),
    trakpak("trakpak", "TrakPak", "TrakPak"),
    matkahuolto("matkahuolto", "Matkahuolto", "Matkahuolto"),
    acscourier("acscourier", "ACS Courier", "ACS Courier"),
    dpd_poland("dpd-poland", "DPD Poland", "波兰DPD"),
    taxydromiki("taxydromiki", "Geniki Taxydromiki", "Geniki Taxydromiki"),
    adicional("adicional", "Adicional Logistics", "Adicional Logistics"),
    cbl_logistica("cbl-logistica", "CBL Logistics", "CBL Logistics"),
    redur_es("redur-es", "Redur Spain", "Redur Spain"),
    siodemka("siodemka", "Siodemka", "Siodemka"),
    exapaq("exapaq", "Exapaq", "Exapaq"),
    cainiao("cainiao", "Aliexpress Standard Shipping", "速卖通线上物流"),
    ets_express("ets-express", "ETS Express", "俄通收"),
    al8856("al8856", "Ali Business Logistics", "阿里电商物流"),
    anjun("anjun", "Anjun Logistics", "安骏物流"),
    quantium("quantium", "Quantium", "冠庭国际物流"),
    xqwl("xqwl", "XQ Express", "星前物流"),
    alpha_fast("alpha-fast", "Alpha Fast", "Alpha Fast快递"),
    omniparcel("omniparcel", "Omni Parcel", "Omni Parcel快递"),
    cdek("cdek", "CDEK Express", "CDEK快递"),
    trackon("trackon", "Trackon Courier", "Trackon"),
    yunda("yunda", "Yunda Express", "韵达快递"),
    postnl_3s("postnl-3s", "PostNL International 3S", "PostNL International 3S"),
    adsone("adsone", "ADSOne", "ADSOne快递"),
    landmark_global("landmark-global", "Landmark Global", "Landmark Global快递"),
    thecourierguy("thecourierguy", "The Courier Guy", "The Courier Guy"),
    smsa_express("smsa-express", "SMSA Express", "SMSA快递"),
    sf_express("sf-express", "S.F Express", "顺丰速递"),
    buylogic("buylogic", "Buylogic", "捷买送"),
    inpost_paczkomaty("inpost-paczkomaty", "InPost Paczkomaty", "InPost Paczkomaty"),
    star_track("star-track", "Star Track Express", "Star Track 快递"),
    qfkd("qfkd", "QFKD Express", "全峰快递"),
    jd("jd", "JD Express", "京东快递"),
    ttkd("ttkd", "TTKD Express", "天天快递"),
    deppon("deppon", "DEPPON", "德邦物流"),
    cacesapostal("cacesapostal", "Cacesa Postal", "Cacesa南美专线"),
    chukou1("chukou1", "Chukou1 Logistics", "出口易"),
    arrowxl("arrowxl", "Arrow XL", "Arrow XL"),
    xdp_uk("xdp-uk", "XDP Express", "XDP Express"),
    imexglobalsolutions("imexglobalsolutions", "IMEX Global Solutions", "IMEX Global Solutions"),
    easy_mail("easy-mail", "Easy Mail", "Easy Mail"),
    idexpress("idexpress", "IDEX", "IDEX"),
    rrdonnelley("rrdonnelley", "RR Donnelley", "RR Donnelley"),
    con_way("con-way", "Con-way Freight", "Con-way Freight"),
    ninjavan("ninjavan", "Ninja Van", "Ninja Van"),
    speedexcourier("speedexcourier", "Speedex Courier", "Speedex Courier"),
    expeditors("expeditors", "Expeditors", "Expeditors"),
    spsr("spsr", "SPSR", "中俄快递SPSR"),
    chronopost_portugal("chronopost-portugal", "Chronopost Portugal", "Chronopost Portugal"),
    dwz("dwz", "DWZ Express", "递五洲国际物流"),
    xpressbees("xpressbees", "XpressBees", "XpressBees"),
    courier_it("courier-it", "Courier IT", "Courier IT"),
    specialised_freight("specialised-freight", "Specialised Freight", "Specialised Freight"),
    ups_mi("ups-mi", "UPS Mail Innovations", "UPS Mail Innovations"),
    dpe_south_africa("dpe-south-africa", "DPE South Africa", "DPE South Africa"),
    dawn_wing("dawn-wing", "Dawn Wing", "Dawn Wing"),
    fastrak_services("fastrak-services", "Fastrak Services", "Fastrak Services"),
    nova_poshta("nova-poshta", "Nova Poshta", "Nova Poshta"),
    md_express("md-express", "MC Express", "茂聪国际物流"),
    uc_express("uc-express", "UC Express", "优速快递"),
    takesend("takesend", "Takesend Logistics", "泰嘉物流"),
    dhl_parcel_nl("dhl-parcel-nl", "DHL Netherlands", "DHL Netherlands"),
    roadbull("roadbull", "Roadbull Logistics", "Roadbull Logistics"),
    dhl_benelux("dhl-benelux", "DHL Benelux", "DHL Benelux"),
    tk_kit("tk-kit", "Tk Kit", "Tk Kit"),
    abf("abf", "ABF Freight", "ABF Freight"),
    couriers_please("couriers-please", "Couriers Please", "Couriers Please"),
    cess("cess", "Cess", "国通快递"),
    bestex("bestex", "Best Express", "百世快递"),
    gofly("gofly", "Gofly", "Gofly"),
    sinoair("sinoair", "SINOAIR", "中外运"),
    italy_sda("italy-sda", "Italy SDA", "意大利SDA"),
    t_cat("t-cat", "T Cat", "黑貓宅急便"),
    fastgo("fastgo", "Fastgo", "速派快递FastGo"),
    pca("pca", "PCA", "PCA"),
    ftd("ftd", "FTD Express", "富腾达快递"),
    shipgce("shipgce", "Shipgce Express", "飞洋快递"),
    wise_express("wise-express", "Wise Express", "万色速递"),
    cnpex("cnpex", "Cnpex", "中邮快递"),
    _1hcang("1hcang", "1hcang", "1号仓"),
    tea_post("tea-post", "Tea post", "亚欧快运TEA"),
    sunyou("sunyou", "Sunyou", "顺友物流"),
    dhlecommerce_asia("dhlecommerce-asia", "DHL Global Mail Asia", "DHL Global Mail Asia"),
    dhl_active("dhl-active", "DHL Active Tracing", "DHL Active Tracing"),
    tnt_reference("tnt-reference", "TNT Reference", "TNT Reference"),
    j_net("j-net", "J-NET Express", "J-NET捷网"),
    jiayi56("jiayi56", "Jiayi Express", "佳怡物流"),
    deltec_courier("deltec-courier", "Deltec Courier", "Deltec Courier"),
    miuson_international("miuson-international", "Miuson Express", "深圳淼信国际物流"),
    espeedpost("espeedpost", "Espeedpost", "易速国际物流"),
    asendia_hk("asendia-hk", "Asendia HK", "Asendia HK"),
    gaticn("gaticn", "GATI Courier", "GATI上海迦递"),
    szdpex("szdpex", "DPEX China", "DPEX国际快递（中国）"),
    tnt_click("tnt-click", "TNT Click", "TNT Click"),
    rufengda("rufengda", "Rufengda", "如风达"),
    mailamericas("mailamericas", "MailAmericas", "MailAmericas"),
    far800("far800", "Far International Logistics", "泛远国际物流"),
    winit("winit", "Winit", "winit万邑通"),
    _360zebra("360zebra", "360zebra", "斑马物联网"),
    auexpress("auexpress", "Auexpress", "澳邮中国快运AuExpress"),
    freakyquick("freakyquick", "freaky quick logistics", "FQ狂派速递"),
    sure56("sure56", "Sure56", "速尔快递"),
    kye("kye", "KUAYUE EXPRESS", "跨越速运"),
    kjkd("kjkd", "Fast Express", "快捷快递"),
    fetchr("fetchr", "Fetchr", "Fetchr"),
    flywayex("flywayex", "Flyway Express", "程光快递"),
    china_russia56("china-russia56", "China Russia56", "俄必达A79"),
    efspost("efspost", "EFSPost", "平安快递"),
    eyoupost("eyoupost", "Eyou800", "易友通"),
    fd_express("fd-express", "FD Express", "方递物流"),
    zes_express("zes-express", "ESHUN International Logistics", "俄顺国际物流"),
    utec("utec", "utec", "UTEC瞬移达"),
    jiaji("jiaji", "CNEX", "佳吉物流"),
    xdexpress("xdexpress", "XDEXPRESS", "迅达速递"),
    _13_ten("13-ten", "13ten", "13ten"),
    _138sd("138sd", "138sd", "泰国138快递"),
    kwt56("kwt56", "KWT Express", "京华达物流"),
    wiseloads("wiseloads", "wiseloads", "wiseloads快递"),
    wndirect("wndirect", "wndirect", "wndirect快递"),
    eurodis("eurodis", "Eurodis", "Eurodis快递"),
    matdespatch("matdespatch", "Matdespatch", "Matdespatch快递"),
    tnt_au("tnt-au", "TNT Australia", "澳大利亚TNT"),
    yakit("yakit", "yakit", "yakit快递"),
    taqbin_hk("taqbin-hk", "TAQBIN HongKong", "香港宅急便"),
    ubonex("ubonex", "UBon  Express", "优邦速运"),
    _8dt("8dt", "Profit Fields", "永利八达通"),
    _2uex("2uex", "2U Express", "优优速递"),
    ane66("ane66", "Ane Express", "安能物流"),
    aus("aus", "Ausworld Express", "澳世速递"),
    ewe("ewe", "EWE global express", "EWE全球快递"),
    huidaex("huidaex", "Huida Express", "美国汇达快递"),
    allekurier("allekurier", "allekurier", "AlleKurier"),
    transrush("transrush", "Transrush", "转运四方"),
    ste56("ste56", "Suteng Logistics", "速腾快递"),
    qexpress("qexpress", "QEXPRESS", "新西兰易达通"),
    chinz56("chinz56", "CHINZ LOGISTICS", "秦远物流"),
    dpd_hk("dpd-hk", "DPD(HK)", "香港DPD"),
    ztky("ztky", "Zhongtie logistic", "中铁物流"),
    idada56("idada56", "Dada logistic", "大达物流"),
    jersey_post("jersey-post", "Jersey Post", "Jersey Post"),
    ninjavan_my("ninjavan-my", "Ninja Van Malaysia", "Ninja Van （马来西亚）"),
    ninjaxpress("ninjaxpress", "Ninja Van Indonesia", "Ninja Van （印度尼西亚）"),
    ninjavan_ph("ninjavan-ph", "Ninja Van Philippines", "Ninja Van (菲律宾)"),
    ninjavan_th("ninjavan-th", "Ninja Van Thailand", "Ninja Van （泰国）"),
    saicheng("saicheng", "Sai Cheng Logistics", "赛诚国际物流"),
    _8europe("8europe", "8europe", "败欧洲"),
    aplus100("aplus100", "A PLUS EXPRESS", "美国汉邦快递"),
    suyd56("suyd56", "SYD Express", "速邮达物流"),
    ocschina("ocschina", "OCS Express", "OCS国际快递"),
    naqel("naqel", "Naqel", "Naqel"),
    parcel("parcel", "Pitney Bowes", "Pitney Bowes"),
    bsi("bsi", "BSI express", "佰事达"),
    jayeek("jayeek", "Jayeek", "Jayeek"),
    blueskyexpress("blueskyexpress", "Blue Sky Express", "蓝天快递"),
    safexpress("safexpress", "Safexpress", "Safexpress"),
    taqbin_my("taqbin-my", "TAQBIN Malaysia", "TAQBIN 马来西亚"),
    shree_tirupati("shree-tirupati", "Shree Tirupati Courier", "Shree Tirupati"),
    imlb2c("imlb2c", "IML Logistics", "IML艾姆勒"),
    hivewms("hivewms", "HiveWMS", "海沧无忧"),
    uskyexpress("uskyexpress", "Uskyexpress", "全酋通Usky"),
    arkexpress("arkexpress", "Ark express", "方舟国际速递"),
    winlink("winlink", "Winlink logistics", "合联国际物流"),
    xpresspost("xpresspost", "Xpresspost", "xpresspost"),
    epacket("epacket", "ePacket", "e邮宝"),
    usps_international("usps-international", "USPS International", "usps-international"),
    dtdc_plus("dtdc-plus", "DTDC Plus", "DTDC Plus"),
    dhl_hong_kong("dhl-hong-kong", "DHL Hong Kong", "香港DHL"),
    sgtwl("sgtwl", "SGT Express", "深港台物流"),
    coe("coe", "COE", "COE"),
    sprintpack("sprintpack", "SprintPack", "SprintPack"),
    lhtex("lhtex", "LHT Express", "联昊通"),
    wanbexpress("wanbexpress", "Wanb Express", "万邦速达"),
    kawa("kawa", "Kawa", "嘉华"),
    kfy("kfy", "iquick fish", "快飞鱼"),
    alljoy("alljoy", "Alljoy", "Alljoy"),
    logistics("logistics", "WEL", "世航通运WEL"),
    un_line("un-line", "Un-line", "Un-line"),
    bab_ru("bab-ru", "BAB international", "北北国际"),
    cnilink("cnilink", "CNILINK", "CNILINK"),
    hkdexpress("hkdexpress", "HKD", "HKD"),
    sxexpress("sxexpress", "SX-Express", "三象速递"),
    jdpplus("jdpplus", "Jdpplus", "美国急递速递"),
    showl("showl", "Showl", "森鸿物流"),
    sendle("sendle", "Sendle", "Sendle"),
    bombino_express("bombino-express", "Bombino Express", "Bombino Express"),
    iepost("iepost", "iepost", "iepost"),
    whistl("whistl", "Whistl", "Whistl"),
    dxdelivery("dxdelivery", "DX Delivery", "DX Delivery"),
    huilogistics("huilogistics", "Hui Logistics", "荟千物流"),
    superoz("superoz", "SuperOZ Logistics", "速配鸥翼"),
    leopardschina("leopardschina", "Leopards Express", "LWE云豹"),
    cbtsd("cbtsd", "Better Express", "北泰物流"),
    overseas_logistics("overseas-logistics", "Overseas Logistics", "Overseas Logistics 印度快递"),
    linexsolutions("linexsolutions", "Linex", "Linex 快递"),
    asmred("asmred", "ASM", "ASM"),
    airwings_india("airwings-india", "Airwings Courier Express India", "Airwings Courier Express India"),
    professional_couriers("professional-couriers", "The Professional Couriers (TPC)", "The Professional Couriers (TPC)"),
    mondialrelay("mondialrelay", "Mondial Relay", "Mondial Relay"),
    bt_exp("bt-exp", "LJS", "利佳顺"),
    asiafly("asiafly", "AsiaFly", "上海亚翔"),
    hanjin("hanjin", "Hanjin Shipping", "韩进物流"),
    njfeibao("njfeibao", "Flying Leopards Express", "金陵飞豹快递"),
    firstflightme("firstflightme", "First Flight Couriers", "First Flight Couriers"),
    jet("jet", "JET", "JET"),
    _360lion("360lion", "360lion Express", "纬狮物联网"),
    hct("hct", "HCT Express", "新竹物流HCT"),
    ldxpress("ldxpress", "LDXpress", "林道快递"),
    doortodoor("doortodoor", "CJ Logistics", "韩国CJ物流"),
    kuajingyihao("kuajingyihao", "K1 Express", "跨境壹号"),
    qi_eleven("qi-eleven", "7-ELEVEN", "7-ELEVEN"),
    orangeconnex("orangeconnex", "ORANGE CONNEX", "橙联股份"),
    _007ex("007ex", "007EX", "俄顺达"),
    js_exp("js-exp", "JS EXPRESS", "急速国际"),
    gaopost("gaopost", "Gaopost", "高翔物流"),
    airfex("airfex", "Airfex", "亚风快递"),
    dbschenker("dbschenker", "DB Schenker", "全球国际货运"),
    ukmail("ukmail", "UK Mail", "UK Mail"),
    yht("yht", "Eshipping", "一海通"),
    myib("myib", "MyIB", "MyIB"),
    fulfillmen("fulfillmen", "Fulfillmen", "Fulfillmen"),
    tuffnells("tuffnells", "tuffnells", "tuffnells"),
    turtle_express("turtle-express", "Turtle express", "海龟国际速递"),
    ceva_logistics("ceva-logistics", "CEVA Logistics", "CEVA物流"),
    ubx_uk("ubx-uk", "UBX Express", "UBX Express"),
    shree_mahabali_express("shree-mahabali-express", "Shree Mahabali Express", "Shree Mahabali Express"),
    ydhex("ydhex", "YDH", "YDH义达物流"),
    quickway("quickway", "Quickway", "瞬程物流"),
    yunlu("yunlu", "YL express", "云路物流"),
    kerryexpress("kerryexpress", "Kerry Express", "Kerry Express"),
    gel_express("gel-express", "GEL Express", "GEL 快递"),
    scorejp("scorejp", "Scorejp", "中国流通王"),
    ldlog("ldlog", "LD Logistics", "龙迅国际物流"),
    xpost("xpost", "XPOST", "XPOST"),
    myaustrianpost("myaustrianpost", "GmbH", "澳邮欧洲专线平邮"),
    cosex("cosex", "Cosex", "慧合物流"),
    ht56("ht56", "Hong Tai", "鸿泰物流"),
    elianpost("elianpost", "E-lian", "易连供应链"),
    btd56("btd56", "Bao Tongda Freight Forwarding", "深圳宝通达"),
    shreemaruticourier("shreemaruticourier", "Shree Maruti Courier", "Shree Maruti Courier"),
    bqc("bqc", "BQC", "BQC百千诚物流"),
    hnfywl("hnfywl", "Fang Yuan", "方圆物流"),
    kerry_tec("kerry-tec", "Kerry Tec", "Kerry Tec"),
    _8256ru("8256ru", "BEL", "BEL北俄国际"),
    cxc("cxc", "CXC", "CXC物流"),
    kke("kke", "King Kong Express", "京广速递"),
    _800best("800best", "Best Express(logistic)", "百世快运"),
    sut56("sut56", "Suto Logistics", "速通物流"),
    yji("yji", "YJI", "延锦国际"),
    speedpak("speedpak", "SpeedPAK", "SpeedPAK物流"),
    zajil("zajil", "Zajil", "Zajil快递"),
    lgs("lgs", "Lazada (LEX)", "Lazada (LGS) 快递"),
    dekun("dekun", "Dekun", "德坤物流"),
    yimidida("yimidida", "YMDD", "壹米滴答"),
    ecpost("ecpost", "ECPOST", "ECPOST"),
    cre("cre", "CRE", "中铁快运"),
    famiport("famiport", "Famiport", "全家快递"),
    e_can("e-can", "Taiwan Pelican Express", "台湾宅配通快递"),
    meest("meest", "Meest Express", "Meest快递"),
    boxc("boxc", "Boxc Logistics", "Boxc"),
    ltian("ltian", "Ltian", "乐天国际"),
    buffaloex("buffaloex", "Buffalo", "Buffalo"),
    sjtsz("sjtsz", "SJTSZ Express", "盛吉泰快递"),
    com1express("com1express", "Come One express", "商壹国际快递"),
    grandslamexpress("grandslamexpress", "Grand Slam Express", "Grand Slam Express"),
    lbexps("lbexps", "LiBang International Logistics", "立邦国际物流"),
    etotal("etotal", "eTotal", "eTotal快递"),
    ueq("ueq", "UEQ", "UEQ"),
    hound("hound", "Hound Express", "Hound Express"),
    eparcel_kr("eparcel-kr", "eParcel Korea", "eParcel Korea"),
    sumxpress("sumxpress", "Sum Xpress", "速玛物流"),
    suning("suning", "SUNING", "苏宁物流"),
    dpd_de("dpd-de", "DPD Germany", "德国 DPD"),
    ledii("ledii", "Ledii", "乐递供应链"),
    hxgj56("hxgj56", "Hanxuan international express", "瀚轩国际物流"),
    kjy("kjy", "KJY Logistics", "跨境翼物流"),
    euasia("euasia", "Euasia Express", "EAX欧亚专线"),
    _1dlexpress("1dlexpress", "1DL Express", "e递诺快递"),
    uvan("uvan", "UVAN Express", "UVAN宇环通快递"),
    nippon("nippon", "Nippon Express", "Nippon日本通运"),
    ninjavan_vn("ninjavan-vn", "Ninja Van Vietnam", "Ninja Van（越南）"),
    guangchi("guangchi", "GuangChi Express", "光驰国际物流"),
    ;

    String code;
    String name;
    String name_cn;

    private CourierEnum(final String code, final String name, final String name_cn) {
        this.code = code;
        this.name = name;
        this.name_cn = name_cn;
    }

    public String getCode() {
        return this.code;
    }

    public String getName() {
        return this.name;
    }

    public String getName_cn() {
        return this.name_cn;
    }

    private static final Map<String, CourierEnum> NAME_MAP = new HashMap<String, CourierEnum>();
    private static final Map<String, CourierEnum> NAME_MAP2 = new HashMap<String, CourierEnum>();
    private static final Map<String, CourierEnum> CODE_MAP = new HashMap<String, CourierEnum>();
    private static final Map<String, CourierEnum> CN_NAME_MAP = new HashMap<String, CourierEnum>();

    static {
        for (CourierEnum x : CourierEnum.values()) {
            NAME_MAP.put(x.name.toUpperCase(), x);
            NAME_MAP2.put(x.name().toUpperCase(), x);
            CODE_MAP.put(x.code.toUpperCase(), x);
            CN_NAME_MAP.put(x.name_cn.toUpperCase(), x);
        }
    }

    public static final boolean contains(String value) {
        return getEnumByValue(value)!=null;
    }

    public static final CourierEnum getEnumByValue(String value) {
        if (value == null) {
            return null;
        }
        value = value.toUpperCase();
        CourierEnum result = getEnumByCode(value);
        if (result != null) {
            return result;
        }
        result = getEnumByName(value);
        if (result != null) {
            return result;
        }
        result = getEnumByName2(value);
        if (result != null) {
            return result;
        }
        return getEnumByCNName(value);
    }

    public static final CourierEnum getEnumByName(String name) {
        if (name != null) {
            return NAME_MAP.get(name.toUpperCase());
        }
        return null;
    }

    public static final CourierEnum getEnumByName2(String name) {
        if (name != null) {
            return NAME_MAP2.get(name.toUpperCase());
        }
        return null;
    }

    public static final CourierEnum getEnumByCode(String code) {
        if (code != null) {
            return CODE_MAP.get(code.toUpperCase());
        }
        return null;
    }

    public static final CourierEnum getEnumByCNName(String name_cn) {
        if (name_cn != null) {
            return CN_NAME_MAP.get(name_cn.toUpperCase());
        }
        return null;
    }

    public static void main(String[] args) {
        CourierEnum a = getEnumByCNName("保加利亚邮政");
        System.out.println(a);
        CourierEnum b = getEnumByName("Česká POšta");
        System.out.println(b);
        CourierEnum c = getEnumByCode("cOrreos-chile");
        System.out.println(c);

        CourierEnum d = getEnumByValue("COURIERS_PLEASE");
        System.out.println(d);

        boolean e = contains("Česká pošta");
        System.out.println(e);

    }


}